### ISSUE TITLE
CI fails on testing ROS_REPO

### ISSUE THREAD

**Issue by aremazeilles** [tecnalia-advancedmanufacturing-robotics/ros_node_test#4]
Using github actions for the CI process, following the indications of [ros industrial](https://github.com/ros-industrial/industrial_ci#for-github-actions):

```yaml
name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
```
CI fails at the testing level on the testing REPO ([details here](https://github.com/tecnalia-advancedmanufacturing-robotics/ros_node_test/runs/945613162?check_suite_focus=true))
For now the related line is commented in the [CI yaml file](https://github.com/tecnalia-advancedmanufacturing-robotics/ros_node_test/blob/master/.github/workflows/industrial_ci_action.yml#L23).
